version: '3'
services:
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
        container_name: mailcatcher
    rabbitmq:
        image: rabbitmq:3.7-management
        container_name: rabbitmq
        ports: [5672, 15672]
